### ISSUE TITLE
Image upload access point needs security screening

### ISSUE THREAD

**Issue by junzhengca** [jackzheng06/microwave-time#1]
Image upload access point currently does not check file types.

**Comment by junzhengca** [comment]
In `api/access_point.php`. There is a function called `base64_to_image($base64_string, $output_file)`.
Currently, it does not check whether or not the base64 string is an image.
This is a potential security issue, since the user may able to upload other script files.


@ianw3214 @EvW1998 @Anurudran 
Does anyone want to take on this issue?

**Comment by ianw3214** [comment]
I'll take it 🌮

**Comment by junzhengca** [comment]
Sounds good, can you just create another branch instead of working on master?

**Comment by junzhengca** [comment]
@ianw3214 
I added another commit, it should work now. You can submit a pull request if you think it is good.
I might implement Docker in the near future, so you can test the app on your own machine.

**Comment by ianw3214** [comment]
The problem should be fixed now, I'm going the merge the branch and close this issue.
