### ISSUE TITLE
Move to Microsoft Cognitive Services

### ISSUE THREAD

**Issue by junzhengca** [jackzheng06/microwave-time#3]
I believe we should move to Microsoft Cognitive Services since we have Azure Pass.
What do you guys think? @ianw3214 @EvW1998 @Anurudran

**Comment by ianw3214** [comment]
I think it's a good idea, not only just to use the pass but also make the machine learning algorithm work a little bit better. Maybe if a lot of people press the same button in a row it will change a lot more and if the time starts swinging around a certain time it will change a lot less. Definitely something worth looking into. @jackzheng06

**Comment by junzhengca** [comment]
Sounds good, I will move the back end from Clarifai to Microsoft Cognitive Service. Since it provides better performance.
I will close this issue now.
